### ISSUE TITLE
Gimbalabs Indonesia Team Meeting #1: 20 January 2023

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/gimbalabs-indonesia#1]
## Gimbalabs Indonesia Meeting: 20 January 2023
- Last Meeting - N/A                           
- Next Meeting - #2 

### Attendees:
Andreas Sosilo (@andreassosilo)
Andy Sibuea (@zicozibu)
Gorga Siagian (@gorgagian123)
Yan Tirta (@YanTirta)
Valdryan Ivandito (@ValdryanIvandito)

### Apologies:
N/A

## Tasks
- [x]  Translate Module 100 : @zicozibu @andreassosilo @gorgagian123 @ValdryanIvandito 
- [x] Contact James regarding access to Canvas Infrastructure @YanTirta 
- [x] Create gimbalabsindonesia@gmail.com -> Google Drive for translation (create folder)

### Gimbalabs Indonesia
- In the Fund 10, @YanTirta , @gorgagian123 , @ValdryanIvandito, Sonny & @andreassosilo will create proposal for Gimbalabs Indonesia
- Meeting with James (Gimbalabs) on Thursday, 01 Dec 2022 at 16:00-17:00 UTC (DONE). Discussion about tokenomics & sustainability -> Next step: build proposal -> agree with the KPI -> completion date
- We will receive GMBL tokens + how to support creating dApps under Gimbalabs
- We will support part of the annual fee for the Canvas (14k USD/year)
- Translation all PPBL content, subtitle for video, weekly coding session (12x sessions)
- Gimbalabs will support -> 1 hour open office per week (for Q&A)
- GitHub repo: https://github.com/cardano-indonesia/gimbalabs-indonesia
- @ValdryanIvandito : share documentation for cardano-cli
- @YanTirta had meeting with James Gimbalabs -> will try to get funding from other resources -> waiting for further information
- @ValdryanIvandito @YanTirta @gorgagian123 @andreassosilo : we need separate meeting to discuss about roadmap
- There will be change in PPBL -> will finish in March 2023 -> need to translate the new material

### GPTE
- https://gpte.gimbalabs.io/
- @andreassosilo @gorgagian123 @ValdryanIvandito : need to finish PPBL course & get the contribution token (Mastery 301, Mastery 302, Mastery 303)
- @andreassosilo (Product Management) + @ValdryanIvandito @gorgagian123 (Software Development) + @YanTirta (Managing Organization)

### Catalyst Fund 10 Proposal
- [Draft proposal](https://docs.google.com/document/d/1LJuVR5-aduE7LjDhNj_etFsZf5OIHRWvnZyULZwZMjk/edit?usp=sharing)

### Gimbalabs PPBL Website
- Link: https://gimbalabs.com/gimbalgrid/4

### Canvas Infrastructure for Gimbalabs Indonesia
- @YanTirta needs to ask James regarding access to https://gimbalabs.instructure.com/
- We need to create a course for PPBL in Indonesian language (copy from existing PPBL v2, but in Indonesian languages)
- Meeting: TBD (next week) 

## Discussion with Yan

A. Continue with the proposed roadmap draft as following : 
1. Use Gimbalabs PPBL to educate developers in Indonesia/Japan/Viet Nam through workshops

2. Translate all PPBL content into Indonesian/Japanese/Vietnamese (PPBL can be found here : https://gimbalabs.com/gimbalgrid/1)

3. Study the existing tools together (cardano-node, cardano-cli, cardano-wallet, cardanocli-js, Mesh, Lucid, Emurgo Serializer Lib, Plutus, Haskell, Blockfrost API, etc.). 

4. Share the knowledge above through weekly/bi-weekly workshops/discussion sessions in Indonesian/Japanese/Vietnamese

5. Do real world projects such as simple dApps (there is a frontend, backend, smart contract), so it is practical learning and not only theoretical through the GPTE

6. Gimbalabs Indonesia/Japan/Viet Nam becomes a place to learn and share together in Indonesian/Japanese/Vietnamese

B. Be eligible to access Gimbalabs GPTE by first finishing the PPBL to receive a "Certification Token"

C. In creation of the proposal, therefore one would need to calculate the compensation expected in translating all PPBL syllabus and providing time to educate upcoming devs

D. By doing so, you do two task at once. Translating and finishing the PPBL to access GPTE

E. This is the link to GPTE (GPTE is a long term goal from Gimbalabs which is part of their tokenomics principle ; Retaining and Growing Value through Participation) : https://gpte.gimbalabs.io/

F. By having access to GPTE we will then have done our point (5) roadmap

G. Awaiting January, GPTE will be forked to GPTE Indonesia, where the Indonesian community can issue task to be completed and also be given a number of GMBL tokens, as a treasury, to rewards those who completes the issued task
