### ISSUE TITLE
Gimbalabs Indonesia Team Meeting #3: 02 September 2023

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/gimbalabs-indonesia#3]
## Gimbalabs Indonesia Team Meeting - 02 September 2023
- Last Meeting - #2                            
- Next Meeting - #4  

### Attendees:
Andreas Sosilo (@andreassosilo)
Yan Tirta (@YanTirta)
Valdryan Ivandito (@ValdryanIvandito)

### Apologies:
N/A

## Tasks
- [ ] Translate Module 204 :@andreassosilo @ValdryanIvandito 
- [x] Inform communities & friends to vote for our Catalyst Fund 10 proposal
- [x] Create folders for "Close Out Report" & "Accounting" @ValdryanIvandito 
- [x] Create Google Docs for Close Out Report (@YanTirta ) & Google Sheet for Accounting (@andreassosilo )
- [x] Inform Gadjah Mada University regarding workshop schedule in November 2023
- [x] Create wallet using Eternl for Gimbalabs Indonesia @ValdryanIvandito 

### 1. Proposal Catalyst Fund 10 for Gimbalabs Indonesia
- Link: https://cardano.ideascale.com/c/idea/100117
- Status: voting (deadline: 14 September 2023)
- Please inform local community & friends to vote our Gimbalabs proposal

### 2. Monthly report to Catalyst IOG + meeting Catalyst Coordinator
- Will be handled by @andreassosilo 

### 3. Accounting & Expenses Sheet for Fund
- Treasurer: @ValdryanIvandito 
- Every input & output of the ADA or native asset need to be documented properly in the Google Sheet
- Create new wallet -> all of the core team will have access to the seed phrase
- Every fund received will be directly converted to DJED (stablecoin) -> there will be fee during swap (e.g. Minswap DEX)

### 4. Closing Report
- Create Google Docs for close-out report since beginning
- Update every workshop recap after we finished deliver the workshop + also Gimbalabs PPBL 2023 Indonesian website link
- Link to Google Docs: TBD -> @ValdryanIvandito will create "Close Out Report" folder + @YanTirta will share one of the close out report example (Google Docs)
- Deadline: June 2024

### 5. Module translation + video subbing
- We have translated until module 203
- There is some problem with module 204 -> @ValdryanIvandito & @andreassosilo need to check the issue
- Video subbing: we need to sub the video also -> try to discuss this one later on

### 6. Kanban board using Trello
- @YanTirta : please give us the Trello link + access for @andreassosilo & @ValdryanIvandito 
- We will put detail on each tasks for each workshop + translation module in the Trello
- Waiting for initial budget from Catalyst IOG

### 7. Schedule workshop + live coding session
- @YanTirta : to inform Gadjah Mada University, that we will start our first and second workshop in November 2023. Coordination with them is needed.
-  Detail: 2 hours workshop + 2 hours live coding session -> for each modules

### 8. Coordination with Gimbalabs
- Coordination with Gimbalabs -> meeting every Wednesday at 20:00 WIB / 13:00 UTC
- Support from James (Gimbalabs) for Q&A session (if needed)

### 9. Recording + YouTube
- Every workshop session will be recorded + uploaded to Komunitas Cardano Indonesia & Gimbalabs YouTube channels
- No need to be edited -> adding intro in the beginning is optional

### 10. Bounties + Andamio
- All of 2000 USD budget for bounties, will be allocated later on after all workshops are finished
- @YanTirta & @ValdryanIvandito : please kindly ask Sebastian Pabon regarding progress about Andamio -> ask them for roadmap in June 2024
